alter table ACCOUNTANDCERTIFICATEMANAGER_CERTIFICATE add column REVOKED boolean ^
update ACCOUNTANDCERTIFICATEMANAGER_CERTIFICATE set REVOKED = false where REVOKED is null ;
alter table ACCOUNTANDCERTIFICATEMANAGER_CERTIFICATE alter column REVOKED set not null ;
